<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('tenants', function (Blueprint $t) { $t->id(); $t->string('name'); $t->string('code')->unique(); $t->string('status')->default('ACTIVE'); $t->timestamps(); });
        Schema::create('organizations', function (Blueprint $t) { $t->id(); $t->foreignId('tenant_id')->constrained()->cascadeOnDelete(); $t->string('name'); $t->string('code'); $t->string('status')->default('ACTIVE'); $t->timestamps(); $t->unique(['tenant_id','code']); });
        Schema::create('users', function (Blueprint $t) { $t->id(); $t->foreignId('tenant_id')->constrained()->cascadeOnDelete(); $t->foreignId('organization_id')->nullable()->constrained()->nullOnDelete(); $t->string('name'); $t->string('email')->unique(); $t->timestamp('email_verified_at')->nullable(); $t->string('password'); $t->string('role')->default('USER'); $t->string('status')->default('ACTIVE'); $t->rememberToken(); $t->timestamps(); });
        Schema::create('employees', function (Blueprint $t) { $t->id(); $t->foreignId('tenant_id')->constrained()->cascadeOnDelete(); $t->foreignId('organization_id')->nullable()->constrained()->nullOnDelete(); $t->string('employee_no'); $t->string('name'); $t->string('email')->nullable(); $t->date('hire_date')->nullable(); $t->string('status')->default('ACTIVE'); $t->timestamps(); $t->unique(['tenant_id','employee_no']); });
        Schema::create('customers', function (Blueprint $t) { $t->id(); $t->foreignId('tenant_id')->constrained()->cascadeOnDelete(); $t->foreignId('organization_id')->nullable()->constrained()->nullOnDelete(); $t->string('customer_code'); $t->string('name'); $t->string('email')->nullable(); $t->string('status')->default('ACTIVE'); $t->timestamps(); $t->unique(['tenant_id','customer_code']); });
        Schema::create('items', function (Blueprint $t) { $t->id(); $t->foreignId('tenant_id')->constrained()->cascadeOnDelete(); $t->string('item_code'); $t->string('name'); $t->string('uom')->default('EA'); $t->string('status')->default('ACTIVE'); $t->timestamps(); $t->unique(['tenant_id','item_code']); });
        Schema::create('projects', function (Blueprint $t) { $t->id(); $t->foreignId('tenant_id')->constrained()->cascadeOnDelete(); $t->foreignId('organization_id')->nullable()->constrained()->nullOnDelete(); $t->string('project_no'); $t->string('name'); $t->foreignId('customer_id')->nullable()->constrained()->nullOnDelete(); $t->date('planned_start')->nullable(); $t->date('planned_finish')->nullable(); $t->decimal('budget',19,2)->default(0); $t->string('status')->default('DRAFT'); $t->timestamps(); $t->unique(['tenant_id','project_no']); });
        Schema::create('journals', function (Blueprint $t) { $t->id(); $t->foreignId('tenant_id')->constrained()->cascadeOnDelete(); $t->foreignId('organization_id')->nullable()->constrained()->nullOnDelete(); $t->string('journal_no'); $t->date('journal_date'); $t->text('description')->nullable(); $t->string('status')->default('DRAFT'); $t->timestamp('posted_at')->nullable(); $t->timestamps(); $t->unique(['tenant_id','journal_no']); });
        Schema::create('journal_lines', function (Blueprint $t) { $t->id(); $t->foreignId('journal_id')->constrained()->cascadeOnDelete(); $t->unsignedInteger('line_no'); $t->string('account_code'); $t->decimal('debit',19,2)->default(0); $t->decimal('credit',19,2)->default(0); $t->string('description')->nullable(); $t->unique(['journal_id','line_no']); });
        Schema::create('purchase_orders', function (Blueprint $t) { $t->id(); $t->foreignId('tenant_id')->constrained()->cascadeOnDelete(); $t->foreignId('organization_id')->nullable()->constrained()->nullOnDelete(); $t->string('po_number'); $t->string('supplier_name'); $t->date('order_date'); $t->decimal('total',19,2)->default(0); $t->string('status')->default('DRAFT'); $t->timestamps(); $t->unique(['tenant_id','po_number']); });
        Schema::create('stock_balances', function (Blueprint $t) { $t->foreignId('tenant_id')->constrained()->cascadeOnDelete(); $t->foreignId('item_id')->constrained()->cascadeOnDelete(); $t->string('warehouse_code'); $t->decimal('quantity',19,4)->default(0); $t->decimal('reserved_quantity',19,4)->default(0); $t->timestamps(); $t->primary(['tenant_id','item_id','warehouse_code']); });
        Schema::create('production_orders', function (Blueprint $t) { $t->id(); $t->foreignId('tenant_id')->constrained()->cascadeOnDelete(); $t->foreignId('organization_id')->nullable()->constrained()->nullOnDelete(); $t->string('order_no'); $t->string('product_name'); $t->decimal('planned_quantity',19,4); $t->decimal('produced_quantity',19,4)->default(0); $t->string('status')->default('CREATED'); $t->timestamps(); $t->unique(['tenant_id','order_no']); });
        Schema::create('assets', function (Blueprint $t) { $t->id(); $t->foreignId('tenant_id')->constrained()->cascadeOnDelete(); $t->foreignId('organization_id')->nullable()->constrained()->nullOnDelete(); $t->string('asset_code'); $t->string('name'); $t->decimal('acquisition_cost',19,2)->default(0); $t->date('commission_date')->nullable(); $t->string('status')->default('REGISTERED'); $t->timestamps(); $t->unique(['tenant_id','asset_code']); });
        Schema::create('work_orders', function (Blueprint $t) { $t->id(); $t->foreignId('tenant_id')->constrained()->cascadeOnDelete(); $t->foreignId('organization_id')->nullable()->constrained()->nullOnDelete(); $t->string('work_order_no'); $t->foreignId('asset_id')->constrained()->cascadeOnDelete(); $t->string('maintenance_type')->default('CORRECTIVE'); $t->string('priority')->default('NORMAL'); $t->string('status')->default('OPEN'); $t->timestamp('planned_start')->nullable(); $t->timestamps(); $t->unique(['tenant_id','work_order_no']); });
        Schema::create('audit_logs', function (Blueprint $t) { $t->id(); $t->foreignId('tenant_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $t->string('action'); $t->string('entity_type')->nullable(); $t->unsignedBigInteger('entity_id')->nullable(); $t->uuid('correlation_id')->nullable()->index(); $t->json('before_state')->nullable(); $t->json('after_state')->nullable(); $t->timestamps(); });
    }

    public function down(): void
    {
        foreach (['audit_logs','work_orders','assets','production_orders','stock_balances','purchase_orders','journal_lines','journals','projects','items','customers','employees','users','organizations','tenants'] as $table) Schema::dropIfExists($table);
    }
};
